"""
Query Expansion / Multi-Query Generation.

Expands a legal research question into semantically related sub-queries
to improve retrieval recall. Uses rule-based expansion (no paid APIs).

Strategy:
1. Original query is always included (never lost).
2. Acronym expansion for common Indian legal terms.
3. Section/article reformulation (e.g. "Section 438 CrPC" → "anticipatory bail").
4. Keyword extraction fallback for short queries.

All expansion is deterministic and fast — no LLM call needed.
Falls back to [question] on any error so retrieval is never blocked.
"""

import re
import logging
from typing import Optional

logger = logging.getLogger(__name__)

# ── Legal acronym/alias expansion ────────────────────────────
_ACRONYM_EXPANSIONS: dict[str, list[str]] = {
    "CrPC": ["Code of Criminal Procedure", "Cr.P.C"],
    "IPC": ["Indian Penal Code"],
    "CPC": ["Code of Civil Procedure"],
    "IEA": ["Indian Evidence Act"],
    "NDPS": ["Narcotic Drugs and Psychotropic Substances Act"],
    "POCSO": ["Protection of Children from Sexual Offences"],
    "PMLA": ["Prevention of Money Laundering Act"],
    "SC": ["Supreme Court of India"],
    "HC": ["High Court"],
    "FIR": ["First Information Report"],
}

# ── Section-to-concept mapping (most-cited Indian provisions) ──
_SECTION_CONCEPTS: dict[str, str] = {
    "section 438": "anticipatory bail",
    "section 437": "regular bail",
    "section 439": "bail sessions court",
    "section 482": "inherent powers high court",
    "section 302": "murder punishment",
    "section 307": "attempt to murder",
    "section 376": "sexual assault rape",
    "section 498a": "domestic cruelty",
    "section 420": "cheating fraud",
    "section 138": "dishonour cheque negotiable instruments",
    "article 21": "right to life personal liberty",
    "article 14": "equality before law",
    "article 19": "freedom of speech expression",
    "article 226": "writ jurisdiction high court",
    "article 32": "writ jurisdiction supreme court",
}


def expand_query(question: str, max_variants: int = 3) -> list[str]:
    """
    Return a list of query variants for multi-query retrieval.

    The original question is always first. Additional variants are
    generated by acronym expansion and section-to-concept mapping.
    The list is deduplicated and capped at max_variants.

    Never raises — returns [question] as fallback on any error.
    """
    try:
        return _expand(question, max_variants)
    except Exception:
        logger.warning("Query expansion failed for '%s', using original", question[:80])
        return [question]


def _expand(question: str, max_variants: int) -> list[str]:
    variants: list[str] = [question]
    q_lower = question.lower()

    # ── 1. Acronym expansion ──────────────────────────────────
    for acronym, expansions in _ACRONYM_EXPANSIONS.items():
        pattern = r"\b" + re.escape(acronym) + r"\b"
        if re.search(pattern, question, re.IGNORECASE):
            for expansion in expansions:
                candidate = re.sub(pattern, expansion, question, flags=re.IGNORECASE)
                if candidate not in variants:
                    variants.append(candidate)
                    if len(variants) >= max_variants:
                        return variants

    # ── 2. Section → concept expansion ───────────────────────
    for section_phrase, concept in _SECTION_CONCEPTS.items():
        if section_phrase in q_lower and concept not in q_lower:
            # Add a variant with the concept alongside the section reference
            concept_query = f"{question} {concept}"
            if concept_query not in variants:
                variants.append(concept_query)
                if len(variants) >= max_variants:
                    return variants

    # ── 3. Conceptual reformulation for bail queries ──────────
    bail_terms = ["bail", "anticipatory bail", "custody", "detention", "arrest"]
    if any(t in q_lower for t in bail_terms) and len(variants) < max_variants:
        reformulated = (
            question
            .replace("anticipatory bail", "pre-arrest bail Section 438")
            .replace("bail conditions", "conditions for granting bail")
        )
        if reformulated != question and reformulated not in variants:
            variants.append(reformulated)

    return variants[:max_variants]
