package com.lexrag.api.dto.response;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * Response from the case comparison pipeline.
 *
 * The structuredComparison field contains the LLM's JSON output:
 *   cases[], comparison{facts/issues/arguments/reasoning/decision/legal_provisions},
 *   similarities[], differences[], conflicting_findings[], key_citations[].
 *
 * All citations in structuredComparison have been verified against the database.
 */
public record CaseComparisonResponse(
        String question,
        /** Raw structured comparison from the LLM (already parsed from JSON). */
        Map<String, Object> structuredComparison,
        /** Citations that were verified valid. */
        List<Map<String, Object>> verifiedCitations,
        /** Citations that failed verification (hallucinations, IDOR attempts, mismatches). */
        List<Map<String, Object>> invalidCitations,
        String confidence,
        Long latencyMs,
        Instant generatedAt,
        String disclaimer
) {
    public static final String LEGAL_DISCLAIMER =
            "This case comparison is generated by an AI research assistant from retrieved document chunks. "
            + "It does not constitute legal advice. Always verify citations against primary sources.";
}
