package com.lexrag.api.dto.response;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Research query result returned to the frontend.
 * Contains the answer, verified citations, and pipeline metadata.
 */
public record ResearchQueryResponse(
        UUID queryId,
        String question,
        String answer,
        List<Map<String, Object>> verifiedCitations,
        String strategy,
        Double confidence,
        Integer retrievedChunks,
        Long latencyMs,
        Instant createdAt,
        String disclaimer
) {
    public static final String LEGAL_DISCLAIMER =
            "This answer is generated by an AI research assistant and may contain errors. "
            + "Always verify citations against primary sources. "
            + "This is not legal advice.";
}
